config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'goals#new'

  resources :goals, except: [:edit, :update] do
    get 'random', action: 'random_show', on: :collection
    resources :comments, except: [:edit, :update] do
      get 'like', shallow: true
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :goal
  belongs_to :writer, class_name: 'User'

  scope :order_by_recent, ->{ order(created_at: :desc) }

  validates :content, presence: true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :writer, class_name: 'User'
  has_many :comments, dependent: :destroy

  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :goals, foreign_key: 'writer_id', class_name: 'Goal', dependent: :destroy
  has_many :comments, foreign_key: 'writer_id', class_name: 'Comment' # destroy dependency: user <- goals <- comments

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def create
    @goal = Goal.find(params[:goal_id])
    comment = @goal.comments.build(comment_params)
    comment.like = 0
    if current_user == @goal.writer
      comment.writer = current_user
    end

    if comment.save
      redirect_to @goal
    else
      # need to show error
      redirect_to @goal
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
  end

  def like
    @comment = Comment.find(params[:comment_id])
    @comment.like += 1

    @comment.save!

    redirect_to :back
  end

private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:new, :show, :random_show]

  def index
    if user_signed_in?
      @goals = current_user.goals
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.writer = current_user

    if @goal.save
      redirect_to @goal
    else
      # need to show error
      render 'new'
    end
  end

  def show
    @goal = Goal.find(params[:id])
    @user = @goal.writer
    @url = goal_url(@goal)
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    redirect_to goals_path
  end

  def random_show
    if Goal.count >= 1
      rand_id = Random.rand(Goal.first.id..Goal.last.id)
      redirect_to goal_path(id: rand_id)
    else
      redirect_to root_path
    end
  end

private
  def goal_params
    params.require(:goal).permit(:content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fb_app_id
    if Rails.env.production?
      return "1519947921626205"
    else
      return "818776511527788"
    end
  end

  def og_title
    content_for(:og_title) || "Give me tips"
  end

  def og_description
    content_for(:og_description) || "나에게 조언을 줘!"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/application/index.html.erb
<div class="inner cover">
  <p class="lead"><%= image_tag "logo.png", class: "img-responsive" %></p>
  <h1 class="cover-heading">2015년 목표는 무엇인가요?</h1>
  <p class="lead">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="당신의 목표를 입력해 주세요.">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div>
  </p>
</div>

app/views/comments/_comment.html.erb
  <p>
    <strong>Writer:</strong>
    <%= comment.writer %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>

  <!-- Authorization of the Goal writer is needed -->
  <p>
    <% link_to 'Destroy Comment', [comment.article , comment] ,
                method: :delete,
                data: { confirm: 'Are you Sure?'} %>
  </p>

app/views/comments/_form.html.erb
<%= form_for [@goal, @goal.comments.build] do |f| %>
<div class="input-group">
  <%= f.text_field :content, class: "form-control", placeholder: "친구에게 조언을 해주세요." %>
  <span class="input-group-btn">
    <%= f.submit class: "btn btn-default", value: "남기기" %>
  </span>
</div>
<% end %>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
  <% if user_signed_in? %>
    <div class="input-group">
      <%= f.text_field :content, class: "form-control input-lg", placeholder: "목표를 입력해보세요" %>
      <span class="input-group-btn">
        <%= f.submit class: "btn btn-default input-lg", value: "도와줘!" %>
      </span>
    </div>
  <% else %>
    <%= f.text_field :content, class: "form-control input-lg", placeholder: "먼저 로그인하세요", disabled: true %>
  <% end %>
<% end %>

app/views/goals/index.html.erb
<div class="inner cover">
 <div>
   <h1 class="cover-heading">2015년 나의 목표</h1>
 </div>
 <hr/>

 <div>
   <ul class="list-group list-advice">
    <% @goals.each do |goal| %>
      <p>
        <a href="<%= goal_path(goal) %>" class="list-group-item">
          <%= goal.content %>
          <span class="pull-right"><%= "+#{goal.comments.count}" %></span>
        </a>
      </p>
    <% end %>
   </ul>
 </div>
</div>

app/views/goals/new.html.erb
<div class="inner cover">
  <p class="lead"><%= image_tag "logo.png", class: "img-responsive logo" %></p>
  <h1 class="cover-heading">2015년 목표는 무엇인가요?</h1>
  <h4>새해 목표를 등록하고 친구들의 조언을 구해보세요!</h4>
  <p class="lead">
    <%= render 'form' %>
  </p>

  <%= link_to "다른 사람은 어떤 목표를 썼을까요?", random_goals_path, class: "btn btn-warning" %>

  
</div>

app/views/goals/show.html.erb
<% content_for :og_title do %><%= "#{@goal.writer.name}님의 새해 목표는?" %><% end %>
<% content_for :og_description do %><%= "#{@goal.writer.name}님의 목표 달성을 도와주세요!" %><% end %>

<div class="inner cover">
  <div>
    <h3 class="cover-heading goal-prev">
      <%= image_tag @user.image %>
      <%= @user.name %>님, 2015년에는!
    </h3>
    <h1 class="cover-heading">"<%= @goal.content %>"</h1>
  </div>
  <hr/>

  <p class="lead">
    <%= render 'comments/form' %>
  </p>
  <div>
    <ul class="list-group list-advice">
      <% @goal.comments.order_by_recent.reject {|c| c.new_record? }.each do |comment| %>
      <li <%= if comment.writer != nil then "style='background-color: #c0c0c0'".html_safe end %> class="list-group-item clearfix">
        <%= comment.content %>
        <% if comment.writer == nil %>
          <% if comment.like == 0 %>
            <%= link_to image_tag('won-fake.png'), current_user == @goal.writer ? goal_comment_like_path(@goal, comment) : "#" , class: "pull-right" %>
          <% else %>
            <%= link_to image_tag('won-true.jpg'), "#", class: "pull-right" %>
          <% end %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
  <p style="width: 62px; margin: 0 auto">
    <% if current_user == @goal.writer %>
    <iframe src="//www.facebook.com/plugins/share_button.php?href=<%= @url.html_safe %>&layout=button&appId=818776511527788" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowTransparency="true"></iframe>
    <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Give me tips</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="title" content="Give me tips">
  <meta name="description" content="나에게 조언을 줘!">
  <meta name="keywords" content="새해, 2015, 조언, 팁, 목표, 계획">
  <meta property="og:site_name" content="Give me tips!">
  <meta property="og:url" content="<%= request.original_url %>">
  <meta property="og:title" content="<%= og_title %>">
  <meta property="og:type" content="article">
  <meta property="og:image" content="<%= asset_url('logo.png') %>">
  <meta property="og:description" content="<%= og_description %>">
  <meta property="fb:app_id" content="<%= fb_app_id %>">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="style-1-cropbar-clipper">
    .en-markup-crop-options {
        top: 18px !important;
        left: 50% !important;
        margin-left: -100px !important;
        width: 200px !important;
        border: 2px rgba(255,255,255,.38) solid !important;
        border-radius: 4px !important;
    }

    .en-markup-crop-options div div:first-of-type {
        margin-left: 0px !important;
    }
  </style>
</head>
<body>
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h2 class="masthead-brand">
            <%= link_to "Give me tips!", root_path %>
          </h2>
          <nav>
            <ul class="nav masthead-nav">
              <% if user_signed_in? %>
                <li class="active"><%= link_to current_user.name + "님", root_path %></li>
                <li><%= link_to "나의 목표", goals_path %></li>
                <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "로그인", omniauth_authorize_path('user', 'facebook') %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
      <%= yield %>
      <div class="mastfoot">
        <div class="inner">
          <p>Copyright By Hwayo.</p>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>